### ISSUE TITLE
enabling emacs binding

### ISSUE THREAD

**Issue by rhoit** [oluc/leafpad#1]
I couldn't be much happy when I saw, emacs.c in the source, but I'm not able to enable it.

`./configure --enable-emacs` isn't having any effect.

I'm using 0.8.18.1 tarball.

Edited:
Sorry if i posted it in wrong place.

**Comment by oluc** [comment]
Hi,
this repository is a fork. You should look at the upstream site http://tarot.freeshell.org/leafpad/ 
I do not know why it does not work.
Note that the configure.ac file tells this feature is experimental:
   https://github.com/oluc/leafpad/search?q=experimental&ref=cmdform

**Comment by rhoit** [comment]
@oluc yeah i realized it after i posted. I have email the author still waiting for response.

**Comment by ghost** [comment]
Really cool dude!
