### ISSUE TITLE
Error creating proxies: Connection closed

### ISSUE THREAD

**Issue by ghost** [oluc/leafpad#2]
I ran the text editor and save the file. In the console gave me just such a mistake:
Error creating proxy: Соединение закрыто (g-io-error-quark, 18)
Error creating proxy: Соединение закрыто (g-io-error-quark, 18)
Error creating proxy: Соединение закрыто (g-io-error-quark, 18)
Error creating proxy: Соединение закрыто (g-io-error-quark, 18)
Error creating proxy: Соединение закрыто (g-io-error-quark, 18)

**Comment by oluc** [comment]
Hi,
I can't read Cyrillic.
Your issue seems to be related to disc access (g-io), check in that direction. 

For leafpad, this repository is just a personal fork. You could look at the upstream site at http://tarot.freeshell.org/leafpad
