### ISSUE TITLE
translation to new language

### ISSUE THREAD

**Issue by tmtfx** [oluc/leafpad#3]
Friulian translation is available for leafpad since 2017-03-10 for the 0.8.16 version (please look at translation project), but I don't know how to contact the developer or file a new request/bug.
Is this the real-maintained repository? Can you add friulian?

Best regards

**Comment by oluc** [comment]
Hi, this is not the official repository, just a clone. 

The official project might be dead/unmaintained, check that from their page, if you get any answer.

To go forward, you could see with your linux distribution, if they want to package it. 
You could also take over the project, maintaining new translations is not very complicated.

Good luck

**Comment by tmtfx** [comment]
Thank you

Il mer 9 mag 2018, 13:58 oluc <notifications@github.com> ha scritto:
